name: 'milestone2_analytics'
version: '1.0.0'
config-version: 2

profile: 'milestone2_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  milestone2_analytics:
    # No schema config needed here anymore
