version: 2

models:
  - name: stg_census_data
    description: Staged census data with basic cleaning
    columns:
      - name: state
        description: State abbreviation
        tests:
          - not_null
      - name: county
        description: County name
      - name: zip
        description: ZIP code
      - name: loaded_at
        description: Timestamp when data was loaded

  - name: stg_school_directory
    description: Staged school directory data with coordinate validation
    columns:
      - name: leaid
        description: Local Education Agency ID
        tests:
          - not_null
      - name: ncessch
        description: NCES school ID
        tests:
          - not_null
      - name: school_name
        description: School name
      - name: latitude
        description: School latitude coordinate
        tests:
          - not_null
      - name: longitude
        description: School longitude coordinate
        tests:
          - not_null

  - name: stg_school_assessments
    description: Staged school assessment data
    columns:
      - name: leaid
        description: Local Education Agency ID
        tests:
          - not_null
      - name: ncessch
        description: NCES school ID
        tests:
          - not_null
      - name: year
        description: Assessment year
        tests:
          - not_null

  - name: stg_location_data
    description: Staged geographic location data
    columns:
      - name: latitude
        description: Latitude coordinate
        tests:
          - not_null
      - name: longitude
        description: Longitude coordinate
        tests:
          - not_null
