version: 2

models:
  - name: dim_school_assessments
    description: Comprehensive view of school assessments with geographic and demographic data
    columns:
      - name: leaid
        description: Local Education Agency ID
        tests:
          - not_null
      - name: ncessch
        description: NCES school ID
        tests:
          - not_null
      - name: school_name
        description: School name
      - name: year
        description: Assessment year
        tests:
          - not_null
      - name: math_test_pct_prof_midpt
        description: Midpoint estimate of math proficiency percentage
      - name: read_test_pct_prof_midpt
        description: Midpoint estimate of reading proficiency percentage
      - name: enrollment
        description: Student enrollment count
